// Emit a .d.ts describing a service's interfaces.
//
// The generated file is types only: no runtime code, no dependency on this
// library at run time beyond the type import, and nothing that parses XML. It
// plugs into the generic `getInterface<T>()` added in 0.6, so a caller gets a
// checked surface for members that are otherwise discovered at run time.

const { returnToTs, signatureToTs } = require('./types');

// 'org.freedesktop.NetworkManager.Device' -> 'OrgFreedesktopNetworkManagerDevice'
function typeName(interfaceName) {
  return interfaceName
    .split('.')
    .map(part => part.replace(/[^A-Za-z0-9]/g, '_'))
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

// A d-bus member name is already a valid identifier, but an argument name from
// introspection is not guaranteed to be.
function paramName(name, index) {
  const cleaned = String(name || '').replace(/[^A-Za-z0-9_$]/g, '_');
  if (!cleaned || /^[0-9]/.test(cleaned)) return `arg${index}`;
  // avoid colliding with reserved words in a parameter position
  return /^(function|new|class|return|default|arguments|eval)$/.test(cleaned)
    ? `${cleaned}_`
    : cleaned;
}

function docComment(lines, indent = '  ') {
  const kept = lines.filter(Boolean);
  if (kept.length === 0) return '';
  if (kept.length === 1) return `${indent}/** ${kept[0]} */\n`;
  return `${indent}/**\n${kept.map(l => `${indent} * ${l}`).join('\n')}\n${indent} */\n`;
}

function emitMethod(method, options) {
  const params = method.args.map((arg, i) => {
    const [type] = signatureToTs(arg.type, options);
    return `${paramName(arg.name, i)}: ${type || 'unknown'}`;
  });
  const returns = returnToTs(method.returns.map(r => r.type).join(''), options);
  const deprecated = method.annotations.find(
    a => a.name === 'org.freedesktop.DBus.Deprecated' && a.value === 'true'
  );
  const signature = `${method.args.map(a => a.type).join('')} -> ${
    method.returns.map(r => r.type).join('') || '()'
  }`;

  return `${docComment(
    [`\`${signature}\``, deprecated ? '@deprecated' : null],
    '  '
  )}  ${method.name}(${params.join(', ')}): DBusPromise<${returns}>;\n`;
}

function emitSignal(signal, options) {
  const params = signal.args.map((arg, i) => {
    const [type] = signatureToTs(arg.type, options);
    return `${paramName(arg.name, i)}: ${type || 'unknown'}`;
  });
  const listener = `listener: (${params.join(', ')}) => void`;
  const doc = docComment(
    [`signal \`${signal.args.map(a => a.type).join('')}\``],
    '  '
  );
  // `this` rather than void: the runtime returns the interface for chaining.
  return (
    `${doc}  on(event: '${signal.name}', ${listener}): this;\n` +
    `${doc}  once(event: '${signal.name}', ${listener}): this;\n`
  );
}

function emitProperty(property, options) {
  const [type] = signatureToTs(property.type, options);
  const lines = [`property \`${property.type}\`, ${property.access}`];
  let out = docComment(lines, '  ');
  out += `  ${property.name}(): DBusPromise<${type || 'unknown'}>;\n`;
  return out;
}

/**
 * @param {object} description   from parseIntrospection()
 * @param {object} options       { service, path, target, moduleSpecifier }
 */
function emitTypes(description, options = {}) {
  const target = options.target || 'classic';
  const moduleSpecifier = options.moduleSpecifier || 'dbus-native';
  const interfaces = description.interfaces.filter(
    // the standard interfaces are already described by the library's own types
    i => !options.skipStandard || !i.name.startsWith('org.freedesktop.DBus.')
  );

  const usesVariant =
    target === 'classic' &&
    JSON.stringify(interfaces).includes('v') &&
    interfaces.some(i =>
      [...i.methods, ...i.signals, ...i.properties].some(m =>
        JSON.stringify(m).includes('v')
      )
    );

  const header = [
    '// Generated by `dbus-native types`. Do not edit.',
    '//',
    options.service ? `// service: ${options.service}` : null,
    options.path ? `// path:    ${options.path}` : null,
    `// target:  ${target}${
      target === 'classic'
        ? ' (value shapes as of 0.x -- regenerate after 2.0)'
        : ''
    }`,
    '',
    `import type { DBusInterface, DBusPromise${
      usesVariant ? ', ClassicVariant' : ''
    } } from '${moduleSpecifier}';`,
    ''
  ]
    .filter(l => l !== null)
    .join('\n');

  const body = interfaces
    .map(iface => {
      const name = typeName(iface.name);
      let out = `/** \`${iface.name}\` */\nexport interface ${name} extends DBusInterface {\n`;
      const parts = [];
      if (iface.methods.length) {
        parts.push(
          iface.methods.map(m => emitMethod(m, { target })).join('\n')
        );
      }
      if (iface.properties.length) {
        parts.push(
          iface.properties.map(p => emitProperty(p, { target })).join('\n')
        );
      }
      if (iface.signals.length) {
        parts.push(
          iface.signals.map(s => emitSignal(s, { target })).join('\n')
        );
      }
      out += parts.join('\n');
      out += '}\n';
      return out;
    })
    .join('\n');

  const names = interfaces.map(i => `  '${i.name}': ${typeName(i.name)};`);
  const map = names.length
    ? `\n/** Every interface on this object, keyed by name. */\nexport interface Interfaces {\n${names.join('\n')}\n}\n`
    : '';

  return `${header}\n${body}${map}`;
}

module.exports = { emitTypes, typeName };
