// @ts-check
'use strict';

const { themes } = require('prism-react-renderer');
const manifest = require('./docs-manifest');

const organizationName = 'sidorares';
const projectName = 'dbus-native';
const repository = `https://github.com/${organizationName}/${projectName}`;

// `docs/` is generated by `scripts/sync-docs.js`, so "Edit this page" has to
// point at the file it was generated from, not at the copy.
const sourceOf = new Map(manifest.map(entry => [entry.out, entry.source]));

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'dbus-native',
  tagline:
    'D-Bus protocol client and server for node.js, implemented in pure JavaScript — no native addons and no build step.',
  favicon: 'img/logo.svg',

  url: `https://${organizationName}.github.io`,
  baseUrl: `/${projectName}/`,
  organizationName,
  projectName,
  trailingSlash: false,

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    // The pages are repository markdown that was never written for MDX, so
    // `<file>` in a table cell and `{ key: value }` in a sentence have to mean
    // what they say. 'detect' parses `.md` as CommonMark and leaves MDX for
    // `.mdx`, of which there is none.
    format: 'detect'
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl: ({ docPath }) =>
            `${repository}/edit/master/${sourceOf.get(docPath) ?? docPath}`
        },
        blog: false,
        theme: {
          customCss: require.resolve('./src/css/custom.css')
        }
      })
    ]
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: { respectPrefersColorScheme: true },
      docs: {
        sidebar: { hideable: true }
      },
      navbar: {
        title: 'dbus-native',
        logo: { alt: '', src: 'img/logo.svg' },
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'docs',
            position: 'left',
            label: 'Docs'
          },
          { to: '/docs/api', label: 'API reference', position: 'left' },
          { to: '/docs/changelog', label: 'Changelog', position: 'left' },
          {
            href: `https://www.npmjs.com/package/${projectName}`,
            label: 'npm',
            position: 'right'
          },
          { href: repository, label: 'GitHub', position: 'right' }
        ]
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Docs',
            items: [
              { label: 'Introduction', to: '/docs/' },
              { label: 'API reference', to: '/docs/api' },
              { label: 'Migrating to 0.14.0', to: '/docs/migrating-to-2.0' },
              { label: 'Deprecations', to: '/docs/deprecations' }
            ]
          },
          {
            title: 'Project',
            items: [
              { label: 'Changelog', to: '/docs/changelog' },
              { label: 'Roadmap', to: '/docs/roadmap' },
              { label: 'Release plan', to: '/docs/release-plan' },
              { label: 'Issues', href: `${repository}/issues` }
            ]
          },
          {
            title: 'Elsewhere',
            items: [
              { label: 'GitHub', href: repository },
              {
                label: 'npm',
                href: `https://www.npmjs.com/package/${projectName}`
              },
              {
                label: 'D-Bus specification',
                href: 'https://dbus.freedesktop.org/doc/dbus-specification.html'
              }
            ]
          }
        ],
        copyright: `MIT licensed. Built with Docusaurus.`
      },
      prism: {
        theme: themes.github,
        darkTheme: themes.dracula,
        additionalLanguages: ['bash', 'diff', 'json']
      }
    })
};

module.exports = config;
